version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3010:3000"
    env_file:
      - .env 
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5131
      MYSQL_DATABASE: yourdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
