version: '3.9'

services:
  nest-app:
    image: 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test:latest
    ports:
      - "3010:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
      MYSQL_DATABASE: yourdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
