name: CI/CD - Build & Deploy to EC2

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCOUNT_ID: 233777024181
  ECR_REPO: nest/test
  ECR_URL: 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
            aws ecr get-login-password --region ap-northeast-2 | \
            docker login --username AWS --password-stdin 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test


  

      - name: Build and push Docker image to ECR
        run: |
          docker build -t 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test:latest .
          docker push 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test:latest

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"



      - name: Write .env file on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/.env
      
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | \
            docker login --username AWS --password-stdin 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test
            docker pull 233777024181.dkr.ecr.ap-northeast-2.amazonaws.com/nest/test:latest
            docker compose -f /home/ubuntu/docker-compose.yml down || true
            docker compose -f /home/ubuntu/docker-compose.yml up -d